apiVersion: cert-manager.io/v1
kind: Certificate 
metadata:
  name: lentilman-dev-tls
spec:
  secretName: lentilman-dev
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lentilman.dev
  dnsNames:
    - lentilman.dev 
    - www.lentilman.dev 