name: Deploy MultiK8s
on:
	push:
		branches:
			- 'test-actions'

env:
	SHA: $(git rev-parse HEAD)

jobs:
	build:
	runs-on: ubuntu-latest
	steps:
		- uses: actions/checkout@v3

		- name: Test
			run: |-
				docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
				docker build -t dockspace9/react-test -f ./client/Dockerfile.dev ./client
				docker run -e CI=true dockspace9/react-test npm test

